version: '3.9'
services:
  postgres:
    container_name: noti
    image: postgres:14.1-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5438:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5438
  #     - DB_USER=user
  #     - DB_PASSWORD=password
  #     - DB_NAME=postgres

volumes:
  pg-data:


  # rabbitmq:
  #   container_name: rabbitmq
  #   image: rabbitmq:3.8.12-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672

#   app:
#     build: .
#     container_name: app
#     image: app
#     environment:
#       PG_URL: 'postgres://user:pass@postgres:5432/postgres'
#       # RMQ_URL: 'amqp://guest:guest@rabbitmq:5672/'
#     ports:
#       - 8080:8080
#     depends_on:
#       - postgres
#       # - rabbitmq

# volumes:
#   pg-data:
