version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.17.1
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/file
    networks:
      - vault-network

  rabbitmq:
    image: cloudamqp/rabbitmq:1.3.0
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    networks:
      - vault-network

  go-backend:
    build: ./path-to-your-go-backend  # Update this path to your Go backend Dockerfile
    container_name: go-backend
    ports:
      - "8080:8080"  # Change this port if needed
    depends_on:
      - vault
      - rabbitmq
    networks:
      - vault-network

volumes:
  vault-data:

networks:
  vault-network:
