app:
  name: "noti"
  version: "1.0.0"

http:
  port: "8072"

logger:
  log_level: "debug"

database:
  type: "sqlite" # or "postgres", "mysql", etc.
  dsn: "noti.db" # For SQLite, this will be the database file name

queue:
  url: "amqp://guest:guest@localhost:5672/"
  reconnect_interval: 5s

vault:
  address: "http://127.0.0.1:8205"
  token: "hvs.CAESIHakNNro6dReSL91MCHjp9xfx-nAs4d-U27A6jeEKSS2Gh4KHGh2cy4ybk1kclN1amtROElTZFRPSUV3RkxqQjM"
