app:
  name: "noti"
  version: "1.0.0"

http:
  port: "8072"

logger:
  log_level: "debug" 

database:
  type: "sqlite"
  dsn: "./data/noti.db"

queue:
  reconnect_interval: "5s"
  max_reconnect_attempts: 3
  heartbeat_interval: "30s"


env: "development"

# vault:
#   address: "http://127.0.0.1:8205"
#   #token: "hvs.CAESIER-LYOx6RcdWJETlXBx94iqUA9ZwalaQBMfXII_MyPbGh4KHGh2cy41Q1kwVU04UHVMQWlyU3R0WW44TWRkYmE"
#   token: "hvs.L5tharyDDPICe6rh9W0gxIj3"

