app:
  name: "noti"
  version: "1.0.0"

http:
  port: "8080"

logger:
  log_level: "debug"

database:
  type: "postgres" # or "mysql"
  postgres:
    pool_max: 10
    dsn: "postgresql://user:password@localhost:5438/postgres"
  mysql:
    dsn: "user:password@tcp(localhost:3306)/dbname"

rabbitmq:
  rpc_server_exchange: "rpc_server"
  rpc_client_exchange: "rpc_client"
  url: "amqp://guest:guest@localhost:5672/"
